[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "annotate_transform"
version = "0.1.0"
requires-python = ">=3.11,<3.12"
dependencies = [
    "jax>=0.4.33,<0.4.38",
    "pytest>=8.3.4",
]

[tool.setuptools]
packages = ["annotate_transform"]
